import Head from "next/head";
import Header from "../components/Header";
import Form from "../components/Form";
import PostFeed from "../components/posts/PostFeed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-4xl text-sky-500">
        <Header label="Accueil" />
        <Form placeholder="Quoi de neuf ?" />
        <PostFeed />
      </div>
    </div>
  );
}
